version: '3.2'

services:
  eureka_server:
    build: eureka-server/
    container_name: eurekaserver
    image: eureka_server:latest
    ports: #mapping the port 
        - "8761:8761"
    networks:
      vs_network:
        ipv4_address: 172.18.0.100

  database_category:
    build: database_category/
    container_name: databasecategory
    image: database_category:latest
    environment:
      - PGPORT=5444
    expose:
      - "5444"
    networks:
      - vs_network
  
  database_product:
    build: database_product/
    container_name: databaseproduct
    image: database_product:latest
    environment:
      - PGPORT=5555
    expose:
      - "5555"
    networks:
      - vs_network

  database_user:
    build: database_user/
    container_name: databaseuser
    image: database_user:latest
    environment:
      - PGPORT=5666
    expose:
      - "5666"
    networks:
      - vs_network

  core-service-category:
    build: core-service-category/
    image: core-service-category
    container_name: coreservicecategory 
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
      - spring.datasource.url=jdbc:postgresql://databasecategory:5444/category
    depends_on:
    - eureka_server
    - database_category
    ports:
      - "8771:8771"
    networks:
      vs_network:
        ipv4_address: 172.18.0.8

  core-service-product:
    build: core-service-product/
    image: core-service-product
    container_name: coreserviceproduct 
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
      - spring.datasource.url=jdbc:postgresql://databaseproduct:5555/product
    depends_on:
    - eureka_server
    - database_product
    ports:
      - "8772:8772"
    networks:
      vs_network:
        ipv4_address: 172.18.0.6

  core-service-user:
    build: core-service-user/
    image: core-service-user
    container_name: coreserviceuser
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
      - spring.datasource.url=jdbc:postgresql://databaseuser:5666/account
    depends_on:
    - eureka_server
    - database_product
    ports:
      - "8773:8773"
    networks:
      vs_network:
        ipv4_address: 172.18.0.7

  composite-service-product-category:
    build: composite-service-product-category/
    image: composite-service-product-category
    container_name: compositeserviceproductcategory
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
    depends_on:
    - eureka_server
    - database_product
    - core-service-category
    - core-service-product
    ports:
      - "8774:8774"
    networks:
      - vs_network

  zuul-application:
    build: zuul-application/
    image: zuul-application
    container_name: zuulapplication
    restart: always
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
    depends_on:
    - eureka_server
    - core-service-category
    - core-service-product
    - core-service-user
    - composite-service-product-category
    ports:
      - "8791:8791"
    networks:
      - vs_network
    
      
  oauthserver:
    build: oauthserver/
    image: oauthserver
    container_name: oauthserver
    restart: always
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
    depends_on:
    - eureka_server
    ports:
      - "4444:4444"
    networks:
      - vs_network
  


networks:
  vs_network:
    #driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24