version: "3.3"

services:
  eureka_server:
    build: eureka-server/
    image: eureka_server
    ports: #mapping the port 
        - "8761:8761"

  database_category:
    build: database_category/
    image: database_category
    ports:
      - "5444:5432"
  
  database_product:
    build: database_product/
    image: database_product
    ports:
      - "5555:5432"

  database_user:
    build: database_user/
    image: database_user
    ports:
      - "5666:5432"
