###Request Product Token
curl coreProductId:coreProductSecret@172.18.0.11:8300/oauth/token -dgrant_type=client_credentials
###Request Category Token
curl coreCategoryId:coreCategorySecret@172.18.0.11:8300/oauth/token -dgrant_type=client_credentials
###Request User Token
curl coreUserId:coreUserSecret@172.18.0.11:8300/oauth/token -dgrant_type=client_credentials
###Request Composite Token
curl compositeId:compositeSecret@172.18.0.11:8300/oauth/token -dgrant_type=client_credentials

###Request Products
curl -i -X GET -H "Authorization: Bearer 953c4637-0852-4603-a3d2-c48436b00dbf" http://172.18.0.6:8772/product 
### Request Products Zuul
curl -i -X GET -H "Authorization: Bearer fbbc9bdd-0e40-423a-a200-043da556580c" http://172.18.0.10:8791/product-service/product
###Request Categories
curl -i -X GET -H "Authorization: Bearer d658103e-0d1d-492f-9dc4-847eb321ecfd" http://172.18.0.8:8771/category
### Request Categories Zuul
curl -i -X GET -H "Authorization: Bearer 57340c9c-29a6-429d-b435-81e11d2d56d3" http://172.18.0.10:8791/category-service/category
### POST User 
curl -i -X POST -H "Authorization: Bearer 1679f38b-49af-4674-9006-625fcd2f1ba3" http://172.18.0.7:8773/user -d '{"username":"sola", "firstname":"olaf", "lastname":"olafson","password":"asdf"}' -H "Content-Type: application/json"
### POST User Zuul
curl -i -X POST -H "Authorization: Bearer 1679f38b-49af-4674-9006-625fcd2f1ba3" http://172.18.0.10:8791/user-service/user -d '{"username":"asdfw", "firstname":"olaf", "lastname":"olafson","password":"asdf"}' -H "Content-Type: application/json"
### GET Product COMPOSITE
curl -i -X GET -H "Authorization: Bearer 75183131-648e-407b-a36a-6bfb2211ec2fc85b0a65-cbf8-492b-87e7-429630368d60" http://172.18.0.9:8774/product

##################################################
######################BACKUP######################
##################################################
curl -H "Accept: application/json" http://user:secret@172.18.0.11:8300/oauth/token -d grant_type=client_credentials #DOESN'T WORK
###Request kommt bei  Oautserver and die respons ist aber error unauthorized
curl -i -H 'Content-Type: code' -X POST 'http://172.18.0.11:8300/oauth/token' -d 'grant_type=client_credentials&client_id=coreProductId&client_secret=coreProductSecret'

###
curl -i -X GET -H "Authorization: OAuth 5f77f153-f167-49e8-a229-f6164855984f" http://172.18.0.6:8772/product  -d 'grant_type=client_credentials&client_id=coreProductId&client_secret=coreProductSecret'
###
curl -H "Accept: application/json" http://my-client-with-secret:apiProductSecret@172.18.0.6:8772/oauth/token -d grant_type=client_credentials
###
curl --user apiProductId:apiProductSecret http://172.18.0.6:8772/products
###
curl -H "Authorization: Bearer 67fb656d-4ddf-4bd7-ad4d-6230a1c377fa" http://localhost:8080/hello
### 
curl -X POST -H "Authorization: Bearer 1f80a890-27ef-4673-89ac-02ee0a4fecdf" http://localhost:8080/fibonacci
###
#Test Without Authorization
curl -X POST http://localhost:8080/fibonacci
### 
curl -X DELETE -H "Authorization: Bearer 64af2e03-7272-4077-824a-91c180a01527" http://localhost:8080/fibonacci
###
POST http://my-client-with-secret:secret@localhost:8080/oauth/token?grant_type=client_credentials HTTP/1.1
Accept: application/json
grant_type=client_credentials
###
GET http://localhost:8080/hello HTTP/1.1
Authorization: Bearer b058b8f7-5459-4d67-be8f-610ada802033