server:
    port: 8791

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
        statusPageUrlPath: /info
        healthCheckUrlPath: /health    
        
zuul:
    ignoredServices: '*'
    routes:
        core-service-category: 
            path: /category-service/**
            serviceId: core-service-category
            stripPrefix: false
        core-service-product: 
            path: /product-service/**
            serviceId: core-service-product
            stripPrefix: false
        composite-product-category: 
            path: /composite/**
            serviceId: composite-product-category
            stripPrefix: false


