server:
    port: 8791

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
        statusPageUrlPath: /info
        healthCheckUrlPath: /health    
        
zuul:
    ignoredServices: '*'
    sensitiveHeaders: Cookie,Set-Cookie
    routes:
        core-service-category: 
            path: /category-service/**
            serviceId: core-service-category
        core-service-product: 
            path: /product-service/**
            serviceId: core-service-product
        core-service-user: 
            path: /user-service/**
            serviceId: user-service-user
        composite-product-category: 
            path: /composite/**
            serviceId: composite-product-category

management:
    endpoints:
        web:
            exposure:
                include: "*"
