server:
    port: 8791

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
        statusPageUrlPath: /info
        healthCheckUrlPath: /health    
        
zuul:
    ignoredServices: '*'
    routes:
        core-service-category: 
            path: /core-service-category/**
        composite-product-category: 
            path: /composite-product-category/**



