server:
    port: 8771


spring:
    application:
        name: core-service-category
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        preferIpAddress: true
        leaseRenewalIntervalInSeconds: 5
        metadataMap:
            instanceId: "${spring.application.name}:${random.value}"
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

security:
  oauth2:
    resource:
      filter-order: 3
      jwk:
        key-set-uri: http://172.18.0.90:8090/auth/oauth2/keys
