server:
    port: 8774
spring:
    application:
        name: composite-product-category
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        preferIpAddress: true
        leaseRenewalIntervalInSeconds: 5
        metadataMap:
            instanceId: "${spring.application.name}:${random.value}"

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
